### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by AbelLykens** [MeshedPotato/Project-Plans#4]
Is English the best language?

I like if the project is shareable with multiple countries (later). 

Dutch might be more accessible for some in NL.

Comments welcome.

**Comment by Dan-Xi** [comment]
I’d go with Dutch, because it’s the most accessible for a lot of people. Just easier and thereby creating more opportunity to contribute. Proposals & workflow in English or bilingual(?).

**Comment by brmdbr** [comment]
I'm used to doing this stuff in English and also I think its more future proof. But I'd like to see more peoples opinions on this. Open for both.

**Comment by AbelLykens** [comment]
Ack, let's stick for English for now. 

If someone wants to discuss: please reopen!
