### ISSUE TITLE
Project logo request

### ISSUE THREAD

**Issue by AbelLykens** [MeshedPotato/Project-Plans#6]
Design for a simple project logo is requested.

* Preferably SVG, clip-art style

Key words:
* The Netherlands
* Mesh Network
* Potato

**Comment by Continu0us** [comment]
A simple potato with an antenna?

**Comment by AbelLykens** [comment]
Works for me ;)

**Comment by Continu0us** [comment]
I was thinking along these lines.

It is just for reference, by the power of MS-Paint

![PotatoRadio](https://user-images.githubusercontent.com/27810365/73128389-069db380-3fcf-11ea-901d-06e5f178d854.jpg)

**Comment by AbelLykens** [comment]
Reopening, I did see another nice suggestion.

**Comment by AbelLykens** [comment]
Saw a suggestion using a fork (doubling as antenna), which I like. We could ask fiverrr?

**Comment by AbelLykens** [comment]
closed: https://github.com/MeshedPotato/meshedpotato.github.io/pull/13
